<a href="https://colab.research.google.com/github/SidhB02/PyTorch_Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR MATH OPERATIONS


1. Add, Subtract, Multiply, Divide, Remainders, Exponents
2. Short-Hand & Long-Hand Format
3. Reassignment

In [3]:
import torch

In [4]:
tensor_a = torch.tensor([1,2,3,8,9])
tensor_b = torch.tensor([4,7,8,6,1])

# DIFFERENT OPS SHORT HAND FOLLOWED BY LONG HAND

Addition

In [5]:
tensor_a + tensor_b

tensor([ 5,  9, 11, 14, 10])

In [8]:
torch.add(tensor_a,tensor_b)

tensor([ 5,  9, 11, 14, 10])

Subtraction

In [9]:
tensor_b - tensor_a

tensor([ 3,  5,  5, -2, -8])

In [10]:
torch.sub(tensor_b,tensor_a)

tensor([ 3,  5,  5, -2, -8])

Multiplication

In [11]:
tensor_a * tensor_b

tensor([ 4, 14, 24, 48,  9])

In [12]:
torch.mul(tensor_a,tensor_b)

tensor([ 4, 14, 24, 48,  9])

Division

In [13]:
tensor_b/tensor_a

tensor([4.0000, 3.5000, 2.6667, 0.7500, 0.1111])

In [14]:
torch.div(tensor_b,tensor_a)

tensor([4.0000, 3.5000, 2.6667, 0.7500, 0.1111])

Modulus

In [15]:
tensor_b % tensor_a

tensor([0, 1, 2, 6, 1])

In [16]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 1, 2, 6, 1])

Exponents / power

In [20]:
tensor_a ** tensor_b

tensor([     1,    128,   6561, 262144,      9])

In [21]:
torch.pow(tensor_a, tensor_b)

tensor([     1,    128,   6561, 262144,      9])